# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Practice4_pb2 as Practice4__pb2


class HelloThereServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.hello_there = channel.unary_unary(
                '/practice4.HelloThereService/hello_there',
                request_serializer=Practice4__pb2.HelloThereRequest.SerializeToString,
                response_deserializer=Practice4__pb2.HelloThereResponse.FromString,
                )


class HelloThereServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def hello_there(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloThereServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'hello_there': grpc.unary_unary_rpc_method_handler(
                    servicer.hello_there,
                    request_deserializer=Practice4__pb2.HelloThereRequest.FromString,
                    response_serializer=Practice4__pb2.HelloThereResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'practice4.HelloThereService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HelloThereService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def hello_there(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/practice4.HelloThereService/hello_there',
            Practice4__pb2.HelloThereRequest.SerializeToString,
            Practice4__pb2.HelloThereResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
